#lang planet dyoo/simply-scheme:2
(define (switch sent)
  (define (replace-word wd)
    (cond ((equal? wd 'i) 'you)
          ((equal? wd 'I) 'you)
          ((equal? wd 'me) 'you)
          ((equal? wd 'Me) 'you)
          ((equal? wd 'you) 'me)
          ((equal? wd 'You) 'me)
          (else wd)))
  (define (replace-sent sent)
    (if (empty? (bf sent))
        (replace-word (first sent))
        (se (replace-word (first sent)) (replace-sent (bf sent)))))
  (if (or (equal? (first sent) 'you) (equal? (first sent) 'You))
      (se 'i (replace-sent (bf sent)))
      (se (replace-sent sent))))